config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root 'application#index'
    resources :projects, only: [:new, :create, :destroy]
    resources :users do
      member do
        patch :archive
      end
    end
  end

  devise_for :users
  root 'projects#index'
  resources :projects, only: [:index, :show, :edit, :update] do
    resources :tickets
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :name, presence: true
  has_many :tickets, dependent: :delete_all
  has_many :roles, dependent: :delete_all
end

app/models/role.rb
class Role < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :project
  belongs_to :author, class_name: "User"
  validates :name, presence: true
  validates :description, presence: true, length: { minimum: 10}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  scope :excluding_archived, lambda {where(archived_at: nil)}

  def to_s
    "#{email} (#{admin? ? 'Admin' : 'user'})"
  end

  def archive
    self.update(archived_at: Time.now)
  end

  def active_for_authentication?
    super && archived_at.nil?
  end

  def inactive_message
    archived_at.nil? ? super : :archived
  end
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
  before_action :authorize_admin!
  def index
  end

  private

  def authorize_admin!
    authenticate_user!
    unless current_user.admin?
      redirect_to root_path, alert: "You must be an admin to do that."
    end
  end
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::ApplicationController
  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      flash[:notice] = 'Project has been created.'
      redirect_to @project
    else
      flash.now[:alert] = 'Project has not been created.'
      render 'new'
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    flash[:notice] = 'Project has been deleted.'
    redirect_to projects_path
  end

  private

  def project_params
    params.require(:project).permit(:name, :description)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :archive]
  def index
    @users = User.excluding_archived.order(:email)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "User has been created."
      redirect_to admin_users_path
    else
      flash.now[:alert] = "User has not been created."
      render "new"
    end
  end

  def show
  end

  def edit
  end

  def update
    if params[:user][:password].blank?
      params[:user].delete(:password)
    end
    if @user.update(user_params)
      flash[:notice] = "User has been updated."
      redirect_to admin_users_path
    else
      flash.now[:alert] = "User has not been updated."
      render "edit"
    end
  end

  def archive
    if @user == current_user
      flash[:alert] = "You cannot archive yourself!"
    else
      @user.archive
      flash[:notice] = "User has been archived."
    end
    redirect_to admin_users_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, :admin)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  rescue_from Pundit::NotAuthorizedError, with: :not_authorized

  private

  def not_authorized
    redirect_to root_path, alert: "You aren't allowed to do that."
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update ]
  def index
    @projects = Project.all
  end

  def show
    authorize @project, :show?
  end

  def edit
  end

  def update
    if @project.update_attributes(project_params)
      flash[:notice] = 'Project has been updated.'
      redirect_to @project
    else
      flash.now[:alert] = 'Project has not been updated.'
      render 'edit'
    end
  end

  private

  def set_project
    @project = Project.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = 'The project you were looking for could not be found.'
    redirect_to projects_path
  end

  def project_params
    params.require(:project).permit(:name, :description)
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_project
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]
  def new
    @ticket = @project.tickets.build
  end

  def create
    @ticket = @project.tickets.build(ticket_params)
    @ticket.author = current_user
    if @ticket.save
      flash[:notice] = "Ticket has been created."
      redirect_to [@project, @ticket]
    else
      flash.now[:alert] = "Ticket has not been created."
      render "new"
    end
  end

  def show
  end

  def edit
  end

  def update
    if @ticket.update(ticket_params)
      flash[:notice] = "Ticket has been updated."
      redirect_to [@project,@ticket]
    else
      flash.now[:alert] = "Ticket has not been updated."
      render "edit"
    end
  end

  def destroy
    @ticket.destroy
    flash[:notice] = "Ticket has been deleted."
    redirect_to @project
  end

  private

  def set_project
    @project = Project.find(params[:project_id])
  end

  def set_ticket
    @ticket = @project.tickets.find(params[:id])
  end

  def ticket_params
    params.require(:ticket).permit(:name,:description)
  end
end

app/helpers/admin/application_helper.rb
module Admin::ApplicationHelper
  def admins_only(&block)
    block.call if current_user.try(:admin?)
  end
end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(*parts)
    unless parts.empty?
      content_for :title do
        (parts << 'Ticketee').join(' - ')
      end
    end
  end

  def admins_only(&block)
    block.call if current_user.try(:admin?)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/admin/application/index.html.erb
<div class="row" id="admin">
  <div class="col-md-9">
    <div class="page-header">
      <h1>Admin Lounge</h1>
    </div>
    <p>
      Welcome to Ticketee's Admin Lounge. Please enjoy your stay.
    </p>
  </div>
  <div class="col-md-3">
    <h2>Admin Links</h2>
    <ul class="nav bav-stacked">
      <li>
        <%= link_to "Users", admin_users_path %>
      </li>
    </ul>
  </div>
</div>

app/views/admin/projects/_form.html.erb
<% if @project.errors.any? %>
<div id="errors_explanation">
  <h2><%= pluralize(@project.errors.count, "errors")%>
    prohibited this project from being saved:</h2>
</div>
<ul>
  <% @project.errors.full_messages.each do |msg| %>
  <li>
    <%= msg %>
  </li>
  <%end%>
</ul>
<%end%>

<%= simple_form_for([:admin,@project]) do |f| %>
<%= f.input :name %>
<%= f.input :description %>
<%= f.button :submit, class: "btn-primary"%>
<%end%>

app/views/admin/projects/new.html.erb
<div class="page-header">
  <h1>New Project</h1>
</div>
<%= render "form", project: @project%>

app/views/admin/users/_form.html.erb
<%= simple_form_for [:admin, user] do |f|%>
  <%= f.input :email %>
  <%= f.input :password %>
  <%= f.input :admin, label: "Is an admin?"%>

  <%= f.button :submit, class: "btn btn-primary"%>
  <%end%>

app/views/admin/users/edit.html.erb
<div class="page-header">
  <h1>Edit User</h1>
</div>

<%= render "form", user: @user %>

app/views/admin/users/index.html.erb
<div class="page-header">
<h1>Users</h1>
<ul class="actions">
<li>
  <%= link_to "New User", new_admin_user_path, class: "new"%>
</li>
</ul>
</div>

<ul>
  <% @users.each do |user|%>
  <li>
    <%= link_to user, [:admin, user] %>
  </li>
  <%end%>
</ul>

app/views/admin/users/new.html.erb
<div class="page-header">
  <h1>New User</h1>
</div>

<%= render "form", user: @user %>

app/views/admin/users/show.html.erb
<div class="page-header">
  <h1><%= @user %></h1>
  <ul class="actions">
    <li>
      <%= link_to "Edit User", [:edit, :admin, @user], class: "edit"%>
    </li>
    <li>
      <%= link_to "Archive User", [:archive, :admin, @user], method: :patch,
      data: {confirm: "Are you sure you want to archive this user?"},
      class: "delete" %>
    </li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
      <% if content_for?(:title) %>
      <%= yield(:title)%>
      <%else%>
      Ticketee
      <%end%>
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <%= link_to "Ticketee", root_path, class: "navbar-brand"%>
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapse">
            <span class="sr-only">Toggle Navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="collapse navbar-collapse" id="collapse">
          <ul class="nav navbar-nav">
            <li class="<%= 'active' if current_page?('/')%>">
              <%= link_to "Home", root_path %>
            </li>
            <%admins_only do %>
            <li>
              <%=link_to "Admin", admin_root_path%>
            </li>
            <%end%>
            <% unless user_signed_in? %>
            <li class="<%= 'active' if current_page?('/users/sign_up')%>">
              <%= link_to "Sign up", new_user_registration_path%>
            </li>
            <li class="<%= 'active' if current_page?('/users/sign_in')%>">
              <%= link_to "Sign in", new_user_session_path %>
            </li>
            <%end%>
          </ul>
          <% if user_signed_in? %>
          <div class="navbar-right">
            <p class="navbar-text">
              Signed in as
              <%= current_user.email %>
            </p>
            <ul class="nav navbar-nav">
              <li>
                <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </div>
          <%end%>
        </div>
      </div>
    </nav>
    <div class="container">
      <% flash.each do |key, message| %>
      <div class="alert alert-<%= key %>">
        <%= message %>
      </div>
      <% end %>
      <%= yield %>

    </div>

  </body>
</html>

app/views/projects/_form.html.erb
<% if @project.errors.any? %>
<div id="errors_explanation">
  <h2><%= pluralize(@project.errors.count, "errors")%>
    prohibited this project from being saved:</h2>
</div>
<ul>
  <% @project.errors.full_messages.each do |msg| %>
  <li>
    <%= msg %>
  </li>
  <%end%>
</ul>
<%end%>

<%= simple_form_for(@project) do |f| %>
<%= f.input :name %>
<%= f.input :description %>
<%= f.button :submit, class: "btn-primary"%>
<%end%>

app/views/projects/edit.html.erb
<div class="page-header">
  <h1>Update Project</h1>
</div>
<%= render "form", project: @project %>

app/views/projects/index.html.erb
<div class="page-header">
  <h1>Projects</h1>
  <% admins_only do %>
  <ul class="actions">
    <li>
      <%= link_to "New Project", new_admin_project_path, class: "new" %>
    </li>
  </ul>
  <%end%>
</div>

<div id="projects">
  <% @projects.each do |project|%>
  <h2><%= link_to project.name, project %></h2>
  <p>
    <%= project.description %>
  </p>
  <%end%>
</div>

app/views/projects/show.html.erb
<div class="page-header">
  <% title(@project.name, "Projects")%>
  <h1><%=@project.name%></h1>
  <ul class="actions">
    <li>
      <%= link_to "Edit Project",
      edit_project_path(@project), class: "edit"%>
    </li>
    <% admins_only do %>
    <li>
      <%= link_to "Delete Project",
      admin_project_path(@project),
      method: :delete,
      data: {confirm: "Are you sure you want to delete this project?"},
      class: "delete"%>
    </li>
    <%end%>
  </ul>
</div>

<div class="page-header">
  <h2>Tickets</h2>

  <ul class="actions">
    <li>
      <%= link_to "New Ticket", new_project_ticket_path(@project), class: "new"%>
    </li>
  </ul>
</div>

<ul id="tickets">
  <% @project.tickets.each do |ticket| %>
  <li>
    #<%= ticket.id%>
    -
    <%= link_to ticket.name, [@project, ticket]%>
  </li>
  <%end%>
</ul>

app/views/tickets/_form.html.erb
<% if @ticket.errors.any? %>
<div id="errors_explanation">
  <h2><%= pluralize(@ticket.errors.count, "errors")%>
    prohibited this project from being saved:</h2>
</div>
<ul>
  <% @ticket.errors.full_messages.each do |msg| %>
  <li>
    <%= msg %>
  </li>
  <%end%>
</ul>
<%end%>

<%= simple_form_for([@project, @ticket]) do |f| %>
<%= f.input :name %>
<%= f.input :description %>
<%= f.button :submit, class: "btn-primary" %>
<%end%>

app/views/tickets/edit.html.erb
<div class="page-header">
  <h1>
    Edit Ticket
    <small><%= @project.name%></small>
  </h1>
</div>
<%= render "form", project: @project, ticket: @ticket %>

app/views/tickets/new.html.erb
<div class="page-header">
  <h1>New Ticket
    <small><%=@project.name%></small>
  </h1>
</div>
<%= render "form", project: @project, ticket: @ticket %>

app/views/tickets/show.html.erb
<div id="ticket">
  <div class="page-header">
    <h1><%= @project.name%></h1>
    <ul class="actions">
      <li>
        <%= link_to "Edit Ticket", [:edit, @project, @ticket], class: "edit"%>
      </li>
      <li>
        <%= link_to "Delete Ticket", [@project, @ticket], method: :delete,
        data: {confirm: "Are you sure you want to delete this ticket?"},
        class: "delete"%>
      </li>
    </ul>
  </div>

  <div class="page-header">
    <h2><%=@ticket.name%></h2>
  </div>
  <%= simple_format(@ticket.description)%>
</div>
<table id="attributes">
  <tr>
    <th>
      Author:
    </th>
    <td>
      <%= @ticket.author.email%>
    </td>
  </tr>
  <tr>
    <th>
      Created:
    </th>
    <td>
      <%= time_ago_in_words(@ticket.created_at)%>ago
    </td>
  </tr>
</table>